name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [master, dev]

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12 # make sure the same version with the one in dev container

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run test
        run: bun test

      - name: Check format
        run: bun run format:check
      
      - name: Check type
        run: bun run typecheck
      
      - name: Check buildable
        run: bun run build