name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12 # make sure the same version with the one in dev container

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run test
        run: bun test
      
      # TODO: check if buildable